version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - "8081:8081"
      - "5081:5081"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mock
    restart: on-failure
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.40
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=mock
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: on-failure

volumes:
  my-db: